export const authors = [
  { url: "jenniferlarmentrout.com", name: "Jennifer L. Armentrout " },
  { url: "https://adrianaherreraromance.com/", name: "Adriana Herrera" },
  { url: "https://www.authorajalexander.com", name: "AJ Alexander" },
  { url: "http://www.alexgraysonbooks.com", name: "Alex Grayson " },
  { url: "https://alexisdaria.com/", name: "Alexis Daria" },
  { url: "https://alihazelwood.com", name: "Ali Hazelwood" },
  { url: "http://Www.alymartinez.com", name: "Aly Martinez" },
  { url: "http://www.amaliehoward.com", name: "Amalie Howard" },
  { url: "https://amandabouchet.com/", name: "Amanda Bouchet" },
  { url: "https://www.authoramieknight.com/", name: "Amie Knight" },
  { url: "http://amojonesbooks.com", name: "Amo Jones" },
  { url: "http://andiejchristopher.com", name: "Andie J. Christopher " },
  { url: "http://romancingandreajoan.com", name: "Andrea Joan" },
  { url: "http://www.andreajohnstonauthor.com", name: "Andrea  Johnston" },
  { url: "https://annmariewalker.com", name: "Ann Marie Walker " },
  { url: "https://www.annabrightbooks.com/", name: "Anna Bright" },
  { url: "https://www.annemalcomauthor.com/", name: "Anne Malcom" },
  { url: "https://www.aprilhuntbooks.com/", name: "April Asher/April Hunt" },
  { url: "https://www.ashleyjadeauthor.com", name: "Ashley Jade" },
  { url: "https://www.aubreywynne.com", name: "Aubrey Wynne" },
  { url: "http://Www.Audreygrey.com", name: "Audrey Grey" },
  { url: "http://www.averyflynn.com", name: "Avery Flynn" },
  { url: "Https://www.authorbceleste.com", name: "B. Celeste" },
  { url: "https://www.facebook.com/authorbbreid", name: "B.B. Reid" },
  { url: "http://www.bturruela.com", name: "BT Urrela" },
  { url: "http://www.brightonwalsh.com", name: "Brighton Walsh" },
  { url: "http://www.brigidkemmerer.com", name: "Brigid Kemmerer" },
  { url: "https://cdreiss.com/", name: "CD Reiss" },
  { url: "https://www.crjanebooks.com/", name: "C.R. Jane" },
  { url: "https://www.facebook.com/calliehartauthor", name: "Callie Hart" },
  { url: "http://www.cambriahebert.com", name: "Cambria Hebert" },
  { url: "http://carrieannryan.com/", name: "Carrie Ann Ryan" },
  { url: "http://www.authorcaseybond.com", name: "Casey L. Bond" },
  { url: "http://menofinked.com", name: "Chelle Bliss" },
  { url: "https://chelseamueller.com", name: "Chelsea Mueller" },
  { url: "http://www.christibarth.com", name: "Christi Barth" },
  { url: "http://www.Christinahovland.com", name: "Christina Hovland" },
  { url: "https://www.christinezolendz.com", name: "Christine Zolendz" },
  {
    url: "http://www.christopherricebooks.com",
    name: "Christopher Rice/ C. Travis Rice",
  },
  { url: "http://cindimadsen.com", name: "Cindi Madsen" },
  { url: "https://corareilly.com", name: "Cora Reilly" },
  { url: "http://Www.authorcoraleejune.com", name: "CoraLee June" },
  { url: "http://www.corinnemichaels.com", name: "Corinne Michaels" },
  { url: "https://crystalashbooks.com", name: "Crystal Ash" },
  { url: "https://www.danirene.com", name: "Dani René" },
  { url: "http://www.AuthorDanielleAllen.com", name: "Danielle Allen" },
  { url: "https://danielleljensen.com/", name: "Danielle L. Jensen" },
  { url: "http://www.darylbanner.com", name: "Daryl Banner" },
  { url: "http://www.DebraAnastasia.com", name: "Debra Anastasia" },
  { url: "http://www.dennysbryce.com", name: "Denny S. Bryce" },
  { url: "http://emmoorebooks.com", name: "E. M. Moore" },
  { url: "http://Www.ejmellow.com", name: "E.J. Mellow" },
  { url: "http://www.edenbutler.com", name: "Eden Butler" },
  { url: "https://elisekova.com/", name: "Elise Kova" },
  { url: "https://www.ellamaven.com/", name: "Ella Maven" },
  { url: "https://www.ellechristensenauthor.com/", name: "Elle Christensen" },
  { url: "https://www.ellecosimano.com/", name: "Elle Cosimano" },
  { url: "https://www.emmascottwrites.com/", name: "Emma Scott" },
  { url: "http://www.erinmallon.com", name: "Erin Mallon" },
  { url: "https://www.evachase.com", name: "Eva Chase/Eva Chance" },
  { url: "http://www.evelmitchell.com", name: "Eve L. Mitchell " },
  { url: "http://www.authorfionacole.com", name: "Fiona Cole" },
  { url: "https://www.facebook.com/authorgiariley", name: "Gia Riley" },
  { url: "http://www.ginalmaxwell.com", name: "Gina L. Maxwell" },
  { url: "http://www.hannahparker.com", name: "Hannah Parker" },
  {
    url: "http://www.heatherhildenbrand.com",
    name: "Heather Hildenbrand/Moxie Rose",
  },
  { url: "http://www.helenahunting.com", name: "Helena Hunting" },
  { url: "http://www.hrmoore.com", name: "HR Moore/Harri Beaumont" },
  { url: "http://www.isabellucero.com", name: "Isabel Lucero " },
  { url: "https://IsobelleCarmichaelwrites.com", name: "Isobelle Carmichael " },
  { url: "http://www.jbreeauthor.com", name: "J Bree" },
  { url: "https://jbengtssonbooks.com", name: "J. Bengtsson" },
  { url: "https://www.authorjlum.com/", name: "J. Lum" },
  { url: "http://www.jrgraybooks.com", name: "J.R. Gray" },
  { url: "http://Www.janineinfantebosco.com", name: "Janine Infante Bosco" },
  { url: "https://www.jannamacgregor.com", name: "Janna MacGregor" },
  { url: "https://jaynefrost.com/", name: "Jayne Frost" },
  { url: "https://jeffekennedy.com/home", name: "Jeffe Kennedy" },
  { url: "https://www.jenlgrey.com/", name: "Jen L. Grey" },
  { url: "https://www.jenniferestep.com/blog/", name: "Jennifer Estep" },
  { url: "http://Www.jessbryantbooks.com", name: "Jess Bryant" },
  {
    url: "https://ajolanthe.wixsite.com/jolialeksander",
    name: "Jolanthe Aleksander",
  },
  { url: "http://www.josieblake.com", name: "Josie Blake" },
  { url: "https://www.juliettecross.com/", name: "Juliette Cross" },
  { url: "http://www.kilynnauthor.com", name: "K.I. Lynn" },
  { url: "https://kamigarcia.com/", name: "Kami Garcia" },
  { url: "https://karengrey.com/", name: "Karen Grey" },
  { url: "http://www.kimberlykincaid.com", name: "Kimberly Kincaid" },
  { url: "http://kishanpaul.net", name: "Kishan Paul" },
  { url: "https://www.krystynaallyn.com/", name: "Krystyna Allyn" },
  { url: "https://lpenelope.com/", name: "L. Penelope" },
  { url: "http://www.lbdunbar.com", name: "L.B. Dunbar" },
  { url: "http://laurakayeauthor.com", name: "Laura Kaye" },
  { url: "http://www.laurathalassa.com/", name: "Laura Thalassa" },
  { url: "http://www.LeaNolan.com", name: "Lea Nolan" },
  { url: "https://www.leteishanewton.com", name: "LeTeisha Newton" },
  { url: "https://www.lexicfoss.com", name: "Lexi C. Foss" },
  { url: "http://www.lexiryan.com", name: "Lexi Ryan" },
  { url: "http://www.authorlisasuzanne.com", name: "Lisa Suzanne" },
  { url: "http://lizzymasonbooks.com", name: "Lizzy Mason" },
  { url: "https://authorluciafranco.com", name: "Lucia Franco" },
  {
    url: "https://www.amazon.com/Lucy-Smoke/e/B073Y39DRG",
    name: "Lucy Smoke/Lucinda Dark",
  },
  { url: "Https://www.lyssakayadams.com", name: "Lyssa Kay Adams" },
  { url: "http://www.authormecarter.com", name: "M.E. Carter" },
  { url: "https://maggiestiefvater.com", name: "Maggie Stiefvater" },
  { url: "https://www.mariavale.com/", name: "Maria Vale" },
  { url: "https://www.tangledtalesofting.com/", name: "Mary Ting" },
  { url: "https://maxwalkerauthor.com/", name: "Max Walker" },
  { url: "http://www.authormeghanquinn.com/", name: "Meghan Quinn" },
  { url: "http://www.mtoppen.com", name: "Melissa Toppen " },
  { url: "https://miasosa.com", name: "Mia Sosa" },
  { url: "https://micaleasmeltzer.com/", name: "Micalea Smeltzer" },
  { url: "http://mollyelee.com", name: "Molly E. Lee" },
  { url: "http://monadshroff.com", name: "Mona Shroff" },
  { url: "http://www.authormonicajames.com", name: "Monica James" },
  { url: "http://naimasimone.com/", name: "Naima Simone" },
  { url: "https://www.natashamadisonauthor.com/", name: "Natasha Madison" },
  { url: "https://www.natashapreston.com/", name: "Natasha Preston" },
  { url: "https://www.nikkisloane.com/", name: "Nikki Sloane" },
  { url: "http://www.NinaBocci.com", name: "Nina Bocci" },
  { url: "http://www.ninacrespo.com", name: "Nina Crespo" },
  { url: "https://patriciadeddy.com", name: "Patricia D. Eddy" },
  { url: "https://darkdangerousdelicious.wordpress.com", name: "Piper Stone" },
  { url: "Https://www.poseyparks.com", name: "Posey Parks " },
  { url: "https://prisoliveras.com/", name: "Priscilla Oliveras" },
  { url: "http://Www.authorrachaelbrownell.com ", name: "Rachael Brownell " },
  {
    url: "https://raquelherreraautor.wixsite.com/my-site",
    name: "Raquel Herrera",
  },
  { url: "https://www.ravenkennedybooks.com/", name: "Raven Kennedy" },
  { url: "https://reanamalori.com", name: "Reana Malori" },
  { url: "https://rebeccarivard.com/", name: "Rebecca Rivard" },
  { url: "http://www.Rebeccayarros.com", name: "Rebecca Yarros" },
  { url: "http://rebeccazanetti.com", name: "Rebecca Zanetti" },
  { url: "http://Www.reneeharless.com", name: "Renee Harless" },
  { url: "https://www.rileyhartwrites.com/", name: "Riley Hart" },
  { url: "http://roanparrish.com", name: "Roan Parrish" },
  { url: "http://www.robincovingtonromance.com", name: "Robin Covington" },
  { url: "https://www.facebook.com/sam.mariano.author", name: "Sam Mariano" },
  { url: "http://www.chasing-romance.com", name: "Samantha Chase" },
  { url: "https://www.facebook.com/saraneyauthor/", name: "Sara Ney " },
  { url: "http://www.sarahdarlingtonauthor.com", name: "Sarah Darlington " },
  { url: "http://sarahmaclean.net", name: "Sarah MacLean" },
  { url: "http://www.sariahwilson.com", name: "Sariah Wilson" },
  { url: "https://scarlettstclair.com", name: "Scarlett St. Clair" },
  { url: "http://www.shailapatelauthor.com", name: "Shaila Patel" },
  { url: "HTTPS://www.siennasnow.com", name: "Sienna Snow" },
  { url: "Https://www.sieralondonauthor.com", name: "Siera London" },
  { url: "http://Sonalidev.com", name: "Sonali Dev" },
  { url: "http://www.sophiejordan.net", name: "Sophie Jordan" },
  { url: "sophielark.com", name: "Sophie Lark " },
  { url: "http://www.staceymariebrown.com ", name: "Stacey Marie Brown " },
  { url: "http://www.terrielaine.com", name: "Terri E. Laine" },
  { url: "https://www.tessabailey.com/", name: "Tessa Bailey" },
  { url: "http://www.tessadare.com", name: "Tessa Dare" },
  { url: "http://tiawritesbooks.com", name: "Tia Giacalone" },
  { url: "http://tifmarcelo.com", name: "Tif Marcelo" },
  { url: "https://tonialeo.com/", name: "Toni Aleo" },
  { url: "https://www.traceyjerald.com", name: "Tracey Jerald" },
  { url: "http://TraceyLivesay.com", name: "Tracey Livesay" },
  { url: "https://tracidouglass.net", name: "Traci Douglass" },
  { url: "https://vanessariley.com", name: "Vanessa Riley" },
  { url: "http://www.wendyhiggins.co/", name: "Wendy Higgins" },
  { url: "http://www.xioaxelrod.com", name: "Xio Axelrod" },
  { url: "https://www.zoeyork.com", name: "Zoe York" },
];
export const authorNames = [
  "Jennifer L. Armentrout ",
  "Adriana Herrera",
  "AJ Alexander",
  "Alex Grayson",
  "Alexis Daria",
  "Ali Hazelwood",
  "Aly Martinez",
  "Amalie Howard",
  "AmandaBouchet",
  "Amie Knight",
  "Amo Jones",
  "Andie J. Christopher ",
  "AndreaJoan",
  "Andrea Johnston",
  "Ann Marie Walker ",
  "Anna Bright",
  "Anne Malcom",
  "April Asher/April Hunt",
  "Ashley Jade",
  "Aubrey Wynne",
  "Audrey Grey",
  "Avery Flynn",
  "B. Celeste",
  "B.B. Reid",
  "BT Urrela",
  "Brighton Walsh",
  "Brigid Kemmerer",
  "CD Reiss",
  "C.R. Jane",
  "Callie Hart",
  "Cambria Hebert",
  "Carrie Ann Ryan",
  "Casey L. Bond",
  "Chelle Bliss",
  "Chelsea Mueller",
  "Christi Barth",
  "Christina Hovland",
  "Christine Zolendz",
  "ChristopherRice/ C. Travis Rice",
  "Cindi Madsen",
  "Cora Reilly",
  "CoraLee June",
  "Corinne Michaels",
  "Crystal Ash",
  "Dani René",
  "Danielle Allen",
  "DanielleL. Jensen",
  "Daryl Banner",
  "Debra Anastasia",
  "Denny S. Bryce",
  "E. M.Moore",
  "E.J. Mellow",
  "Eden Butler",
  "Elise Kova",
  "Ella Maven",
  "ElleChristensen",
  "Elle Cosimano",
  "Emma Scott",
  "Erin Mallon",
  "Eva Chase/EvaChance",
  "Eve L. Mitchell ",
  "Fiona Cole",
  "Gia Riley",
  "Gina L. Maxwell",
  "Hannah Parker",
  "Heather Hildenbrand/Moxie Rose",
  "Helena Hunting",
  "HRMoore/Harri Beaumont",
  "Isabel Lucero ",
  "Isobelle Carmichael ",
  "J Bree",
  "J. Bengtsson",
  "J. Lum",
  "J.R. Gray",
  "Janine Infante Bosco",
  "Janna MacGregor",
  "Jayne Frost",
  "Jeffe Kennedy",
  "Jen L. Grey",
  "Jennifer Estep",
  "Jess Bryant",
  "Jolanthe Aleksander",
  "Josie Blake",
  "Juliette Cross",
  "K.I.Lynn",
  "Kami Garcia",
  "Karen Grey",
  "Kimberly Kincaid",
  "Kishan Paul",
  "Krystyna Allyn",
  "L. Penelope",
  "L.B. Dunbar",
  "Laura Kaye",
  "LauraThalassa",
  "Lea Nolan",
  "LeTeisha Newton",
  "Lexi C. Foss",
  "Lexi Ryan",
  "Lisa Suzanne",
  "Lizzy Mason",
  "Lucia Franco",
  "Lucy Smoke/Lucinda Dark",
  "Lyssa Kay Adams",
  "M.E. Carter",
  "Maggie Stiefvater",
  "Maria Vale",
  "MaryTing",
  "Max Walker",
  "Meghan Quinn",
  "Melissa Toppen ",
  "Mia Sosa",
  "MicaleaSmeltzer",
  "Molly E. Lee",
  "Mona Shroff",
  "Monica James",
  "Naima Simone",
  "Natasha Madison",
  "Natasha Preston",
  "Nikki Sloane",
  "Nina Bocci",
  "Nina Crespo",
  "Patricia D. Eddy",
  "Piper Stone",
  "Posey Parks ",
  "PriscillaOliveras",
  "Rachael Brownell ",
  "Raquel Herrera",
  "Raven Kennedy",
  "ReanaMalori",
  "Rebecca Rivard",
  "Rebecca Yarros",
  "Rebecca Zanetti",
  "ReneeHarless",
  "Riley Hart",
  "Roan Parrish",
  "Robin Covington",
  "Sam Mariano",
  "Samantha Chase",
  "Sara Ney ",
  "Sarah Darlington ",
  "Sarah MacLean",
  "SariahWilson",
  "Scarlett St. Clair",
  "Shaila Patel",
  "Sienna Snow",
  "SieraLondon",
  "Sonali Dev",
  "Sophie Jordan",
  "Sophie Lark ",
  "Stacey Marie Brown",
  "Terri E. Laine",
  "Tessa Bailey",
  "Tessa Dare",
  "Tia Giacalone",
  "Tif Marcelo",
  "Toni Aleo",
  "Tracey Jerald",
  "Tracey Livesay",
  "Traci Douglass",
  "Vanessa Riley",
  "Wendy Higgins",
  "Xio Axelrod",
  "Zoe York",
];
